export interface Employee {
  id: number;
  name: string;
  position: string;
  department: string;
  email: string;
  phone: string;
  birthday: string;
  location: string;
  avatar: string;
  joinDate: string;
}

export const departments = [
  "Tất cả phòng ban",
  "Ban Giám Đốc",
  "Phòng Kinh Doanh",
  "Phòng Marketing",
  "Phòng Sản Xuất",
  "Phòng Kế Toán",
  "Phòng IT",
  "Phòng Nhân Sự",
  "Phòng Logistics",
];

export const employees: Employee[] = [
  {
    id: 1,
    name: "Phạm An Khánh",
    position: "IT",
    department: "Phòng IT",
    email: "nguyenvana@wana.com",
    phone: "0901 234 567",
    birthday: "15/03/1995",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/avatar-Khanh.png",
    joinDate: "01/06/2022",
  },
  {
    id: 2,
    name: "Trần Thị B",
    position: "HR Manager",
    department: "Phòng Nhân Sự",
    email: "tranthib@wana.com",
    phone: "0902 345 678",
    birthday: "22/07/1990",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-5.png",
    joinDate: "15/03/2019",
  },
  {
    id: 3,
    name: "Lê Minh C",
    position: "Marketing Executive",
    department: "Phòng Marketing",
    email: "leminhc@wana.com",
    phone: "0903 456 789",
    birthday: "08/11/1993",
    location: "Hà Nội",
    avatar: "/assets/images/employee-6.png",
    joinDate: "10/01/2021",
  },
  {
    id: 4,
    name: "Phạm Thị D",
    position: "Accountant",
    department: "Phòng Kế Toán",
    email: "phamthid@wana.com",
    phone: "0904 567 890",
    birthday: "30/04/1992",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "20/08/2020",
  },
  {
    id: 5,
    name: "Hoàng Văn E",
    position: "Sales Manager",
    department: "Phòng Kinh Doanh",
    email: "hoangvane@wana.com",
    phone: "0905 678 901",
    birthday: "12/09/1988",
    location: "Đà Nẵng",
    avatar: "/assets/images/employee-5.png",
    joinDate: "05/11/2017",
  },
  {
    id: 6,
    name: "Vũ Thị F",
    position: "Production Supervisor",
    department: "Phòng Sản Xuất",
    email: "vuthif@wana.com",
    phone: "0906 789 012",
    birthday: "18/02/1991",
    location: "Bình Dương",
    avatar: "/assets/images/employee-6.png",
    joinDate: "01/04/2018",
  },
  {
    id: 7,
    name: "Đặng Minh G",
    position: "CEO",
    department: "Ban Giám Đốc",
    email: "dangminhg@wana.com",
    phone: "0907 890 123",
    birthday: "05/06/1975",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "01/01/2010",
  },
  {
    id: 8,
    name: "Bùi Thị H",
    position: "Logistics Coordinator",
    department: "Phòng Logistics",
    email: "buithih@wana.com",
    phone: "0908 901 234",
    birthday: "25/12/1994",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "15/07/2021",
  },
  {
    id: 9,
    name: "Ngô Văn I",
    position: "Sales Executive",
    department: "Phòng Kinh Doanh",
    email: "ngovani@wana.com",
    phone: "0909 012 345",
    birthday: "14/08/1996",
    location: "Hà Nội",
    avatar: "/assets/images/employee-5.png",
    joinDate: "01/09/2022",
  },
  {
    id: 10,
    name: "Trịnh Thị K",
    position: "Content Creator",
    department: "Phòng Marketing",
    email: "trinhthik@wana.com",
    phone: "0910 123 456",
    birthday: "03/01/1997",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-6.png",
    joinDate: "20/03/2023",
  },
  {
    id: 11,
    name: "Lý Văn L",
    position: "IT Support",
    department: "Phòng IT",
    email: "lyvanl@wana.com",
    phone: "0911 234 567",
    birthday: "19/05/1998",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "10/06/2023",
  },
  {
    id: 12,
    name: "Phan Thị M",
    position: "Chief Accountant",
    department: "Phòng Kế Toán",
    email: "phanthim@wana.com",
    phone: "0912 345 678",
    birthday: "11/10/1985",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "01/01/2015",
  },
  {
    id: 13,
    name: "Dương Văn N",
    position: "QA Engineer",
    department: "Phòng Sản Xuất",
    email: "duongvann@wana.com",
    phone: "0913 456 789",
    birthday: "27/07/1993",
    location: "Bình Dương",
    avatar: "/assets/images/employee-5.png",
    joinDate: "05/05/2020",
  },
  {
    id: 14,
    name: "Tô Thị O",
    position: "Recruiter",
    department: "Phòng Nhân Sự",
    email: "tothio@wana.com",
    phone: "0914 567 890",
    birthday: "09/03/1995",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-6.png",
    joinDate: "15/02/2022",
  },
  {
    id: 15,
    name: "Hà Minh P",
    position: "CFO",
    department: "Ban Giám Đốc",
    email: "haminhp@wana.com",
    phone: "0915 678 901",
    birthday: "21/11/1978",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "01/03/2012",
  },
  {
    id: 16,
    name: "Chu Thị Q",
    position: "Brand Manager",
    department: "Phòng Marketing",
    email: "chuthiq@wana.com",
    phone: "0916 789 012",
    birthday: "14/06/1989",
    location: "Hà Nội",
    avatar: "/assets/images/employee-7.png",
    joinDate: "01/08/2019",
  },
  {
    id: 17,
    name: "Đinh Văn R",
    position: "Warehouse Manager",
    department: "Phòng Logistics",
    email: "dinhvanr@wana.com",
    phone: "0917 890 123",
    birthday: "06/04/1987",
    location: "Bình Dương",
    avatar: "/assets/images/employee-5.png",
    joinDate: "20/10/2016",
  },
  {
    id: 18,
    name: "Lưu Thị S",
    position: "Key Account Manager",
    department: "Phòng Kinh Doanh",
    email: "luuthis@wana.com",
    phone: "0918 901 234",
    birthday: "31/08/1991",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-6.png",
    joinDate: "01/02/2021",
  },
  {
    id: 19,
    name: "Vương Văn T",
    position: "Plant Manager",
    department: "Phòng Sản Xuất",
    email: "vuongvant@wana.com",
    phone: "0919 012 345",
    birthday: "16/12/1982",
    location: "Bình Dương",
    avatar: "/assets/images/employee-7.png",
    joinDate: "15/05/2014",
  },
  {
    id: 20,
    name: "Mai Thị U",
    position: "COO",
    department: "Ban Giám Đốc",
    email: "maithiu@wana.com",
    phone: "0920 123 456",
    birthday: "02/09/1980",
    location: "Hồ Chí Minh",
    avatar: "/assets/images/employee-7.png",
    joinDate: "01/06/2011",
  },
];
