"use client";

import DOMPurify from "dompurify";

type RichTextProps = {
  html: string;
  className?: string;
};

/** Render HTML generated by TinyMCE after removing unsafe markup and attributes. */
export function RichText({ html, className = "" }: RichTextProps) {
  const safeHtml = DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true },
  });

  return <div className={className} dangerouslySetInnerHTML={{ __html: safeHtml }} />;
}

export function hasRichTextContent(html?: string) {
  if (!html) return false;

  const plainText = DOMPurify.sanitize(html, { ALLOWED_TAGS: [] })
    .replace(/&nbsp;/g, " ")
    .trim();

  return plainText.length > 0;
}