"use client";

import { useEffect, useState } from "react";

type RichTextProps = {
  html: string;
  className?: string;
};

/** Render HTML generated by TinyMCE after removing unsafe markup and attributes. */
export function RichText({ html, className = "" }: RichTextProps) {
  const [safeHtml, setSafeHtml] = useState("");

  useEffect(() => {
    let active = true;
    void import("dompurify").then(({ default: DOMPurify }) => {
      if (!active) return;
      setSafeHtml(DOMPurify.sanitize(html, { USE_PROFILES: { html: true } }));
    });
    return () => {
      active = false;
    };
  }, [html]);

  return <div className={className} dangerouslySetInnerHTML={{ __html: safeHtml }} />;
}

export function hasRichTextContent(html?: string) {
  if (!html) return false;

  const plainText = html
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&#160;/g, " ")
    .trim();

  return plainText.length > 0;
}
